name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK & NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-36" "build-tools;36.0.0" "ndk;25.2.9519653"
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/cmdline-tools/latest/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make gcc g++

    - name: Patch libchewing CMakeLists
      run: |
        sed -i 's|add_subdirectory(data)|install(DIRECTORY data/ DESTINATION share/libchewing/data FILES_MATCHING PATTERN "*")|' app/src/main/cpp/libs/libchewing/CMakeLists.txt

    - name: Debug patched CMakeLists
      run: |
        echo "---- Showing lines 150 to 180 in CMakeLists.txt ----"
        sed -n '150,180p' app/src/main/cpp/libs/libchewing/CMakeLists.txt

    - name: Build APK
      run: |
        ./gradlew --stop
        ./gradlew clean
        ./gradlew :app:assembleRelease

    - name: List generated APK files
      run: |
        echo "Listing all files in app/build/outputs/apk/:"
        find app/build/outputs/apk/ -type f

    - name: Upload release APKs
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: app/build/outputs/apk/**/*.apk
        retention-days: 90
