name: Build APK

# 觸發條件
on:
  push:
    branches:
      - main      # 推送到 main 分支就自動編譯
  workflow_dispatch:  # 手動觸發也可用

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 下載專案程式碼
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ 安裝 JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3️⃣ 安裝 Android SDK + Build Tools + NDK
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 21
        build-tools: '21.1.2'
        ndk: '21.4.7075529'

    # 4️⃣ 安裝指定 Gradle 版本
    - name: Install Gradle 8.13
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.13'

    # 5️⃣ 編譯 APK
    - name: Build APK
      run: ./gradlew :app:assembleRelease --stacktrace

    # 6️⃣ 上傳 APK 作為 Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
