name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 21
        build-tools: '21.1.2'
        ndk: '21.4.7075529'

    - name: Install Gradle 8.13
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.13'

    - name: Build APK
      run: ./gradlew :app:assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 90
